### Restaurant Ordering System API Tests
@baseUrl = http://localhost:3000/api

### Root endpoint
GET http://localhost:3000


### USERS

### Get all users
GET {{baseUrl}}/users

### Get user by ID
GET {{baseUrl}}/users/1

### Create new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "first_name": "Alice",
  "last_name": "sam",
  "email": "alicee@example.com",
  "phone_number": "0745678901",
  "password": "passs789",
  "user_type": "customer"
}

### Update user
PUT {{baseUrl}}/users/2
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.updated@example.com",
  "phone_number": "0712345678",
  "user_type": "customer"
}

### Delete user
DELETE {{baseUrl}}/users/6


### register  a user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "Sam",
  "last_name": "Smith",
  "email": "samsmiikithkamau@example.com",
  "phone_number": "1234567890",
  "password": "password133",
  "user_type": "user"
}

### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "samsmiikiththkamau@example.com",
  "password": "password133"
}


